AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Gemfile'

Metrics/LineLength:
  Max: 256

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
